### PR TITLE
Added new GPG key used by HP for signing packages

### PR DESCRIPTION
**Pull request by ruzickap**
Hello

It looks like HP added new GPG key for signing their packages.
Search for "New GPG signatures are required for 2015!" http://downloads.linux.hp.com/SDR/

I need to use "http://downloads.linux.hp.com/hpPublicKey2048_key1.pub" as well when installing the packages.

Please check it.

PetrR

### CODE REVIEW

**Comment by razorsedge** [comment]
@ruzickap Thank you for your submission. Could you please resubmit a new PR against the develop branch? Thanks!

**Comment by ruzickap** [comment]
Hello. 

These changes are already in developer branch :-) Next time I need to check it properly.

Thank you

PetrR

**Comment by razorsedge** [comment]
@ruzickap I do not see them in my `develop` branch...

**Comment by ruzickap** [comment]
Hello. 

My bad - it should be there now: https://github.com/razorsedge/puppet-hp_mcp/pull/10

Thanks

PetrR

**Pull request closed without merging**
